### ISSUE TITLE
Allow `node-part` to be self-closing

### ISSUE THREAD

**Issue by benmccann** [tbondwilkinson/dom-parts#2]
Allow `node-part` to be self-closing for XHTML compatibility. See https://developer.mozilla.org/en-US/docs/Glossary/Void_element#self-closing_tags

I would find `<?node-part ?/>` to be easier to read as it's clearer that it's a void element

**Comment by tbondwilkinson** [comment]
There's been some discussion of this.

It gets a little thorny with the parser if we want this, because I believe there's no spec today for void processing instructions because processing instructions do not have open and end tags the same way that HTML tags do. So it may be out of scope for now just because the parsing implications are unknown and the TAG folks may push back on any parser changes due to security risks.

**Comment by zcorpan** [comment]
Self-closing in XML doesn't apply to processing instructions. PIs can't have children, and the suggested syntax isn't allowed syntax in XML.

The HTML parser doesn't support processing instructions at all.

**Comment by tbondwilkinson** [comment]
Work has moved to webcomponents repo, https://github.com/WICG/webcomponents/blob/gh-pages/proposals/DOM-Parts.md
