### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by benmccann** [tbondwilkinson/dom-parts#3]
Having some examples of usage would help. E.g. how do I call `getParts`? Are things like `document.getParts()` and `document.getElementById('myid').getParts()` valid?

**Comment by tbondwilkinson** [comment]
Thank you for the issue! I will add more to the README and close this out. `document.getParts()` is valid, but there is no Element API as of yet. It's something we've considered, but you probably want the nearest `PartRoot`. `getParts()` is otherwise ambiguous whether you want all child parts or just parts attached to a specific element.
